---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    # Tell Dependabot to never update the packages listed in requirements.txt
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "mashumaro"
      - dependency-name: "orjson"
      - dependency-name: "websockets"
      - dependency-name: "yarl"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    # Tell Dependabot to never update the packages listed in requirements.txt
    ignore:
      - dependency-name: "aiohttp"
      - dependency-name: "mashumaro"
      - dependency-name: "orjson"
      - dependency-name: "websockets"
      - dependency-name: "yarl"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
