---
name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 🏗 Extract version from __version__.py
        id: get_version
        run: |
          VERSION=$( grep "__version__" src/pyhaopenmotics/__version__.py | cut -d'"' -f2 )
          echo "extracted_version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🚀 Draft Release
        uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # v7.4.0
        with:
          config-name: release-drafter.yml # the default, loads '.github/release-drafter.yml'
          # This forces release-drafter to use your file's version
          # instead of calculating its own
          version: ${{ steps.get_version.outputs.extracted_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
