---
name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🏗 Extract version from __version__.py
        id: get_version
        run: |
          VERSION=$( grep "__version__" src/pyhaopenmotics/__version__.py | cut -d'"' -f2 )
          echo "extracted_version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🚀 Draft Release
        uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        with:
          config-name: release-drafter.yml # the default, loads '.github/release-drafter.yml'
          # This forces release-drafter to use your file's version
          # instead of calculating its own
          version: ${{ steps.get_version.outputs.extracted_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
